# Generated by Django 3.2.4 on 2023-09-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Departamento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Estudiante', models.CharField(max_length=50)),
                ('Apellido_Estudiante', models.CharField(max_length=50)),
                ('ID_Carrera', models.PositiveIntegerField()),
                ('ID_Usuario', models.PositiveIntegerField()),
            ],
        ),
    ]
