# Generated by Django 4.2.5 on 2023-10-01 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20230928_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Carrera', models.CharField(max_length=50)),
                ('Activo', models.PositiveIntegerField(default=1)),
                ('ID_Departamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.departamento')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='administrador',
            name='Activo',
            field=models.PositiveIntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='ID_Usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='Activo',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='ID_Usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='Mail_Estudiante',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='Activo',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profesor',
            name='Activo',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profesor',
            name='Carrera_Profesor',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='ID_Usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seccion',
            name='Activo',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='estudiante_seccion',
            name='ID_Estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.estudiante'),
        ),
        migrations.AlterField(
            model_name='estudiante_seccion',
            name='ID_Seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.seccion'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='ID_Seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.seccion'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='ID_Departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.departamento'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='ID_Departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.departamento'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='ID_Materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.materia'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='ID_Profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.profesor'),
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='ID_Estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.estudiante'),
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='ID_Materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.materia'),
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='ID_Profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.profesor'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='ID_Carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.carrera'),
        ),
    ]
