# Generated by Django 4.2.5 on 2023-10-10 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_administrador_id_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Imagenes/Imagenes_Administrador'),
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='Trimestre',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Imagenes/Imagenes_Estudiantes'),
        ),
        migrations.AddField(
            model_name='materia',
            name='Codigo_Materia',
            field=models.CharField(default='IDS', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Imagenes/Imagenes_Profesor'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='Activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='Activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='Activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='Activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='Activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='Activo',
            field=models.BooleanField(default=True),
        ),
    ]
