# Generated by Django 4.2.5 on 2023-10-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_administrador_imagen_calificaciones_trimestre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='Horario',
            field=models.CharField(default='lun 12/2', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
    ]
