# Generated by Django 4.2.5 on 2023-10-13 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_seccion_horario_delete_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccion',
            name='Horario',
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dia', models.PositiveIntegerField()),
                ('Hora_inicio', models.PositiveIntegerField()),
                ('Hora_final', models.PositiveIntegerField()),
                ('ID_Seccion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.seccion')),
            ],
        ),
    ]
