# Generated by Django 3.2.4 on 2023-09-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Administrador', models.CharField(max_length=50)),
                ('Apellido_Administrador', models.CharField(max_length=50)),
                ('Mail_Administrador', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante_Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Estudiante', models.PositiveIntegerField()),
                ('ID_Seccion', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Seccion', models.PositiveIntegerField()),
                ('Dia', models.PositiveIntegerField()),
                ('Hora_inicio', models.PositiveIntegerField()),
                ('Hora_final', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Materia', models.CharField(max_length=50)),
                ('ID_Departamento', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Profesor', models.CharField(max_length=50)),
                ('Apellido_Profesor', models.CharField(max_length=50)),
                ('Mail_Profesor', models.EmailField(max_length=254, unique=True)),
                ('ID_Departamento', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Profesor', models.PositiveIntegerField()),
                ('ID_Materia', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario_Usuario', models.CharField(max_length=50)),
                ('Contrasena_Usuario', models.CharField(max_length=50)),
                ('Rol_Usuario', models.PositiveIntegerField()),
                ('ID_Cliente', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='ID_Usuario',
        ),
    ]
